# Generated by Django 4.2.30 on 2026-04-20 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(help_text='Pickup address')),
                ('service_type', models.CharField(choices=[('laundry_ironing', 'Laundry & Ironing'), ('dry_cleaning', 'Dry Cleaning'), ('garment_alteration', 'Garment Alteration & Repairs'), ('industrial_cleaning', 'Industrial Cleaning'), ('post_construction', 'Post Construction Cleaning'), ('fumigation', 'Fumigation'), ('home_deep_cleaning', 'Home Deep Cleaning'), ('pickup_delivery', 'Pickup & Delivery Only')], max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_slot', models.CharField(choices=[('morning', 'Morning (8AM – 12PM)'), ('afternoon', 'Afternoon (12PM – 4PM)'), ('evening', 'Evening (4PM – 7PM)')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('needs_pickup', models.BooleanField(default=True, verbose_name='Free Pickup Required')),
                ('needs_delivery', models.BooleanField(default=True, verbose_name='Free Delivery Required')),
                ('estimated_items', models.PositiveIntegerField(blank=True, help_text='Approximate number of items/bags', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('before_after', 'Before & After'), ('workspace', 'Our Workspace'), ('team', 'Our Team'), ('equipment', 'Equipment')], default='workspace', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('before_image', models.ImageField(blank=True, help_text='For before/after items', null=True, upload_to='gallery/before/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('laundry', 'Laundry'), ('cleaning', 'Cleaning'), ('specialty', 'Specialty')], default='laundry', max_length=20)),
                ('description', models.TextField()),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, default='per item', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Heroicon or emoji name', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text='e.g. 98%, 5000+, 3 Years', max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
